# Generated by Django 5.0 on 2024-01-12 23:55

from django.db import migrations, models

import pyheat1d_web.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Data de criação")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Data de modificação")),
                ("input_file", models.CharField(max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("I", "Simulação pronta para execução"),
                            ("R", "Rodando"),
                            ("S", "Simulação executada"),
                            ("F", "Simulação Falhou"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                ("tag", models.SlugField(unique=True, verbose_name="Tag")),
                (
                    "length",
                    models.FloatField(
                        default=1.0, validators=[pyheat1d_web.core.models.greater_than_zero], verbose_name="Comprimento"
                    ),
                ),
                (
                    "ndiv",
                    models.IntegerField(
                        default=1000,
                        validators=[pyheat1d_web.core.models.greater_than_zero],
                        verbose_name="Numero de divisões",
                    ),
                ),
                (
                    "dt",
                    models.FloatField(
                        default=0.1,
                        validators=[pyheat1d_web.core.models.greater_than_zero],
                        verbose_name="Passo de Tempo",
                    ),
                ),
                (
                    "nstep",
                    models.IntegerField(
                        default=1000,
                        validators=[pyheat1d_web.core.models.greater_than_zero],
                        verbose_name="Número de Passos",
                    ),
                ),
                ("initialt", models.FloatField(default=0.0, verbose_name="Temperatura Inicial")),
                ("lbc_value", models.FloatField(default=10.0, verbose_name="Temperatura a esquerda")),
                ("rbc_value", models.FloatField(default=-10.0, verbose_name="Temperatura a direita")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
