# Generated by Django 5.0 on 2024-01-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Data de criação")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Data de modificação")),
                ("input_file", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("I", "Simulação pronta para execução"),
                            ("R", "Rodando"),
                            ("S", "Simulação executada"),
                            ("F", "Simulação Falhou"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                ("tag", models.SlugField(unique=True, verbose_name="Tag")),
                ("length", models.FloatField(default=1.0, verbose_name="Comprimento")),
                ("ndiv", models.IntegerField(default=1000, verbose_name="Numero de divisões")),
                ("dt", models.FloatField(default=0.1, verbose_name="Passo de Tempo")),
                ("nstep", models.IntegerField(default=1000, verbose_name="Número de Passos")),
                ("initialt", models.FloatField(default=0.0, verbose_name="Temperatura Inicial")),
                ("lbc_value", models.FloatField(default=10.0, verbose_name="Temperatura a esquerda")),
                ("rbc_value", models.FloatField(default=-10.0, verbose_name="Temperatura a direita")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
