# Generated by Django 5.0 on 2024-01-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="celery_task",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
