# Generated by Django 5.0 on 2024-02-19 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="tag",
            field=models.SlugField(verbose_name="Tag"),
        ),
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.UniqueConstraint(fields=("tag", "user"), name="unique_tag_user"),
        ),
    ]
