# Generated by Django 5.0 on 2024-01-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Simulação prota para execução"),
                    ("R", "Rodando"),
                    ("S", "Simulação executada"),
                    ("F", "Simulação Falhou"),
                ],
                default="I",
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
