# Generated by Django 5.0 on 2024-01-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_simulation_created_at_simulation_modified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="dt",
            field=models.FloatField(default=0.1, verbose_name="Passo de Tempo"),
        ),
        migrations.AddField(
            model_name="simulation",
            name="initialt",
            field=models.FloatField(default=0.0, verbose_name="Temperatura Inicial"),
        ),
        migrations.AddField(
            model_name="simulation",
            name="lbc_value",
            field=models.FloatField(default=10.0, verbose_name="Temperatura a esquerda"),
        ),
        migrations.AddField(
            model_name="simulation",
            name="length",
            field=models.FloatField(default=1.0, verbose_name="Comprimento"),
        ),
        migrations.AddField(
            model_name="simulation",
            name="ndiv",
            field=models.IntegerField(default=1000, verbose_name="Numero de divisões"),
        ),
        migrations.AddField(
            model_name="simulation",
            name="nstep",
            field=models.IntegerField(default=1000, verbose_name="Número de Passos"),
        ),
        migrations.AddField(
            model_name="simulation",
            name="rbc_value",
            field=models.FloatField(default=-10.0, verbose_name="Temperatura a direita"),
        ),
    ]
