FROM python:3.11-slim-bullseye

ARG USER_DIR=/home/app

# set work directory
WORKDIR $USER_DIR

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VIRTUALENVS_CREATE=false

# Create the app user
RUN groupadd app && useradd -g app app && mkdir -p $USER_DIR

# install depedencies for postgres
RUN apt-get update && apt-get install -y\
    gcc\
    libpq-dev\
    && rm -rf /var/lib/apt/lists/*

# copy project
RUN pip install --upgrade pip && pip install poetry

# install dependencies
copy pyproject.toml poetry.lock /home/app/

RUN poetry install --no-interaction --no-cache

COPY . .

RUN chown -R app:app $USER_DIR
USER app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
